name: mrs_example
root: ./
startup_window: crazyflies_start
pre_window: |
  source <%= @settings["setup_name"] %>
  source /root/ros2_ws/install/setup.bash 
  source /opt/ros/iron/setup.bash 
windows:
#  - crazyflies_start:
#      layout: tiled
#      panes:
#        - ros2 launch mrs_crazyflies_exp cf_velmux_launch.py
#        - history -s "ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args --remap cmd_vel:=/cf_1/cmd_vel"
  - visualization:
      layout: tiled
      panes:
        - ros2 launch rosbridge_server rosbridge_websocket_launch.xml
        - ros2 run rviz2 rviz2 -d config.rviz
#        - history -s 'ros2 bag record -s mcap --all'


 
